version: '3'
services:
  guess:
    build: ./guesslord
    ports:
      - "6969:6969"
    restart: "always"
    environment:
      - "PORT=6969"

  monster:
    build: ./monster
    ports:
      - "6970:80"
    restart: "always"

  camera:
    build: ./camera
    ports:
      - "6968:22"
    restart: "always"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=ismart12 #optional
      - USER_NAME=camera #optional