version: '3'
services:
  guess:
    build: ./guesslord
    ports:
      - "6969:6969"
    restart: "always"
    environment:
      - "PORT=6969"

  monster:
    build: ./monster
    ports:
      - "6970:80"
    restart: "always"